#! /bin/bash

command -v pandoc >/dev/null 2>&1 || { echo >&2 "I require pandoc but it's not installed.  Aborting."; exit 1; }

command -v ipython >/dev/null 2>&1 || { echo >&2 "I require ipython but it's not installed.  Aborting."; exit 1; }

ipython nbconvert --to html *.ipynb